services:

  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    group_add:
      - "105" # 'render' group
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: Europe/Zurich
    ports:
      - 8092:8096 # HTTP
      - 8910:8920 # HTTPS
    volumes:
      - /mnt/jellyfin/config:/config
      - /mnt/jellyfin/cache:/config/cache
      - /mnt/jellyfin/cache/transcodes:/transcodes
      - /mnt/data/videos:/data:ro
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
    logging:
      driver: journald
