source $VIMRUNTIME/defaults.vim
set background=dark
set t_Co=256

" fix ctrl+arrow not deleting stuff in tmux
" https://superuser.com/a/402084/1099716
if &term =~ '^screen'
    " tmux will send xterm-style keys when its xterm-keys option is on
    execute "set <xUp>=\e[1;*A"
    execute "set <xDown>=\e[1;*B"
    execute "set <xRight>=\e[1;*C"
    execute "set <xLeft>=\e[1;*D"
endif
