services:
  fes:
    image: caddy:2
    container_name: fes
    env_file: .env
    environment:
      EMAIL: ${EMAIL}
      TZ: Europe/Zurich
    ports:
      - 80:80
      - 443:443
      # - 127.0.0.1:2019:2019
    volumes:
      - /mnt/www/fes/Caddyfile:/etc/caddy/Caddyfile
      - /mnt/www/fes/data:/data
      - /mnt/www/fes/config:/config
    extra_hosts:
      - lanhost:${LAN_IP}
    restart: unless-stopped
    logging:
      driver: journald
